### PR TITLE
Fixed content length check on MobileServiceHttpClient.cs

### PR DESCRIPTION
**Pull request by jcbdev**

### CODE REVIEW

**Comment by Bejasc** [comment]
@dhei this PR relates to a now [well documented and easily reproducible issue ](https://github.com/Azure/azure-mobile-apps-net-client/issues/514). Much more context can be found throughout this thread. 

Could we please have this looked at for merging in the very near future? 
There are many of us experiencing this issue.

**Comment by ChaseFlorell** [comment]
@MatkovIvan will we be able to see a release for this soon? Since we can't easily rollback our VS installs, the path forward is to get a new nuget package out.

**Comment by dhei** [comment]
Hey @jcbdev @Bejasc @ChaseFlorell,

Sorry for the delay in response. 

We appreciate the PR. We understand the importance and urgency of this fix. We plan to release a fix for this issue and we will share the ETA of the release as soon as we have one.

**Comment by ChaseFlorell** [comment]
@dhei it would appear as though this has been approved by 2 reviewers. Can we at minimum publish a nuget as a pre-release?

**Pull request merged**
