### PR TITLE
Delete support for Windows Phone8.1 Silverlight

### PR DESCRIPTION
**Pull request by pragnagopa**

### CODE REVIEW

**Comment by dhei** [comment]
Can you remove those silverlight projects from `Microsoft.WindowsAzure.Mobile.Managed_Windows_VS15.sln` as well?

The rest looks good to me. :+1:

**Comment by dhei** [comment]
:+1:

**Comment by dhei** [comment]
:shipit:

**Comment by pragnagopa** [comment]
Closing this PR for now. Will reopen when we decide to do a major version release of the client

**Pull request closed without merging**
