### PR TITLE
(#215) Added formatter to NewGuid.ToString()

### LINKED ISSUE #215: Inconsistent formatting of Guid primary keys
[On the server](https://github.com/Azure/azure-mobile-apps-net-server/blob/master/src/Microsoft.Azure.Mobile.Server.Entity/EntityDomainManager.cs#L120), a PK is created as such:

```
Guid.NewGuid().ToString("N");
```

[On the client](https://github.com/Azure/azure-mobile-services/blob/master/sdk/Managed/src/Microsoft.WindowsAzure.MobileServices/Table/Sync/MobileServiceSyncTable.cs#L70), a PK is created as such:

```
Guid.NewGuid().ToString();
```

So it may, or may not, have hyphens.

I'm not a database expert, but common sense tells me the hyphens would slow down a query over a very large table.

And even if not so, this has caused us some problems when we deal with PKs in our system, we need to first clean them.

Unless this is because of some weird implementation detail that I don't understand, please consider fixing it so it is consistent. Preferably without hyphens.

### PR DESCRIPTION
**Pull request by adrianhall**
Fixes #215.

Also added Microsoft.Bcl and Microsoft.Bcl.Build to the UWP.E2ETest so it runs properly.  I've checked these files in as well.

### CODE REVIEW

**Comment by jiberan** [comment]
@adrianhall  Why was this changed? This change makes it incompatible with uniqueidentifier datatype in SQL server.

**Comment by adrianhall** [comment]
It shouldn't - it's still a GUID.  It's just formatted as a compressed string instead.

**Comment by jiberan** [comment]
This code is generating GUID for entities which are likely by stored into SQL on server-side. This type of formatting will cause Conversion failed exception in case of uniqueidentifier datatype in SQL.

**Comment by adrianhall** [comment]
If you are following the recommended version, the storage of the ID will be a string, not a uniqueidentifier.  This change makes the IDs generated on the client and server side the same format - it's not a change in functionality.  In other words, if you were using the client SDKs before and not setting the IDs manually, then you would be bumping into your issue, which is derived by the fact that the ID we support is a string, not a uniqueidentifier.

**Comment by jiberan** [comment]
you are right, in recommended version is indeed string, not uniqueidentifier. Is there any reason why was chosen string instead of ui?

**Comment by adrianhall** [comment]
It gives developers more flexibility in how to construct identifiers.  Any string can be used.  We use guid strings by default because we can guarantee their uniqueness.  However, sometimes there is a reason to go with a different format.

**Pull request merged**
