### PR TITLE
Convert projects to use .NET Standard 1.1

### LINKED ISSUE #190: Add support for .NET Standard
Customer reported [issue](https://social.msdn.microsoft.com/Forums/en-US/c7f419f7-b434-40e8-9dc2-9e26a8cec9c7/azure-mobile-sdk-netstandard?forum=azuremobile&prof=required).

Currently you can't install the Microsoft.Azure.Mobile.Client package to a netstandard project because certain dependencies are incompatible producing the following error:

Microsoft.Azure.Mobile.Client 2.1.0 is not compatible with .NETStandard,Version=v1.3.
Microsoft.Bcl 1.1.10 is not compatible with .NETStandard,Version=v1.3.
Microsoft.Net.Http 2.2.29 is not compatible with .NETStandard,Version=v1.3.
Some packages are not compatible with .NETStandard,Version=v1.3.

Need to add support for [.Net standard](https://docs.microsoft.com/en-us/dotnet/articles/standard/library)

### PR DESCRIPTION
**Pull request by twsouthwick**
A couple of thoughts/issues with this at the moment:
- As part of this conversion, support for Windows Phone 8.0 was dropped as .NET Standard 1.1 is needed for the core functionality and Windows Phone 8.0 only supports .NET Standard 1.0. All other targets remain the same. This can be fixed, but would make the project a bit more complicated - is this a target that is desired going forward?
- Support for building E2E tests with local projects or package reference is not supported with NuGet v3.0
  This will require at least VS 2015 to open/edit
- This updates Newtonsoft.Json to 9.0.1 as it supports .NET Standard natively. There are some breaking changes to serialization (there are individual commits to fix those)
- This specifies Xamarin.Android to us SDK 5.1 as none had been specified.
- There are some binding redirect issues with iOS and Android builds that I couldn't track down.

Fixes #190

### CODE REVIEW

**Comment by dhei** [comment]
Hi @twsouthwick, your PR is much appreciated. Mobile Apps team is discussing internally targeting our client SDK to .NET Standard so we are glad to see your PR. The goal for us is moving to .NET Standard 1.3 in the next few months and your PR targeting 1.1 is definitely aligned with this goal. Moving to 1.1 means to drop Windows Phone Silverlight 8.1 (wp80), and moving to 1.3 would drop Windows Phone 8.1 (wpa81) and Windows Store 8.1 (win81). 

We are currently in the progress of release version 3.0 this week and we will review your PR next week.

Thank you.

**Comment by aalmada** [comment]
@dhei Hi! Just a reminder that it's been 3 months already. We are all trying to port our projects to netstandard and version 3.0.3 still doesn't fix the issue. Thanks.

**Comment by adrianhall** [comment]
.NETStandard integration is on our roadmap, but our backwards compatibility rules and resourcing plan have it delayed.  This PR contains most of the updates, so you can just fork and re-build.  We'll get to this PR once we get to v4.0 release work.

**Comment by adrianhall** [comment]
@twsouthwick - we are now at a point where we can look at this.  Unless you have objections, I'm going to produce a fork and replicate your PR with the latest codebase.  If you want to adjust so that the merge conflicts are resolved, please let me know and I'll let you do the work.

We will also bump the version to 4.0.0 during this PR.

**Comment by twsouthwick** [comment]
Hi @adrianhall I'm fine doing the work. There are some orthogonal issues here, so I'll submit separate PRs for those.

**Comment by twsouthwick** [comment]
@adrianhall One thing to consider since you are planning on having this a major change: Do you want support for the same platforms, or are you okay dropping support for older platforms (such as WinPhone 8.0)?

**Comment by adrianhall** [comment]
I think we want to move to .NETStandard 1.2 or 1.3 - I'm ok with dropping support for Windows 8.0 and Windows Phone 8.0 in the v4.0.0 release (which is what this will become)

**Comment by twsouthwick** [comment]
Ok. After looking more at the code (and having done multiple conversions to .NET Standard), I'm not sure about the original direction I took with this. The project right now is bundling two libraries with every platform: a platform specific and a portable. Instead of doing this, have you thought about using shared projects and having a single library for each platform, but have it the same name? Or can you get all that you need from .NET Standard and are hoping to eliminate any platform specific code?

**Comment by adrianhall** [comment]
It's more of a platform intent.  We need to support Xamarin.iOS, Xamarin.Android, Xamarin.Forms (Windows 8.1, Windows Phone 8.1, UWP, iOS, Android), UWP, Windows Phone 8.1 and Windows 8.1.

There are two problematic areas that always come up - the first is identity.  We use Xamarin.Auth for the Xamarin components and native web forms for the others.  The second is the offline sync cache, which uses SQLitePCLRaw for the offline store.

We need a single library, so the same code can be used in a cross-platform solution (e.g. when we have a Xamarin Forms app that covers UWP, iOS and Android).

Let's move this to the equivalent bug ID #190.  I think we are going to need an extended conversation with the team, and you may end up closing this pull request and opening a new one anyhow.

**Comment by twsouthwick** [comment]
Sounds good. I"ll close this PR and we can discuss there.

**Pull request closed without merging**
