### PR TITLE
Update Newtonsoft.JSON to 9.0.1

### PR DESCRIPTION
**Pull request by twsouthwick**
This is part of the work needed to support .NET Standard (see #223). Since it requires some code changes (mostly in the tests), I thought it would be good to include as a separate PR. I don't have the ability to build the Mac code, and not familiar with Xamarin in general, so I was only able to catch the tests that I could run on Windows.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@twsouthwick__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (tasou). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by adrianhall** [comment]
Thanks @twsouthwick - I've got the ability to build the iOS unit and e2e tests, so we'll get that done internally before we merge.

**Comment by adrianhall** [comment]
@pvbchak Can you review and merge?  This is a single part of #190 but useful overall since our JSON library is way out of date.

**Comment by adrianhall** [comment]
Quick update - E2E tests are running and there are some failures coming out of the JSON Deserializer.  Since this affects the JSON deserializer, I want to ensure they are just test problems and not problems with the JSONSerializer changes that were made.

**Pull request merged**
