### PR TITLE
Updating e2e nuget references to 2.0.0-rc

### PR DESCRIPTION
**Pull request by gb92**
Will need to fix the target strings in the future as those strings don't match for many of our dependencies, but this should allow NuGet package restore

### CODE REVIEW

**Comment by phvannor** [comment]
:+1:

**Comment by gb92** [comment]
This is probably unnecessary since we did yet another release.

**Comment by phvannor** [comment]
Is there a new PR that puts them at 2.0 or this one will be updated?  Should we just close it?

**Comment by danderson00** [comment]
This PR is superceded by https://github.com/Azure/azure-mobile-apps-net-client/pull/40

**Pull request closed without merging**
